#!/bin/bash

usage()
{
	echo "Usage: docker-bash <CONTAINER_ID> [COMMAND...]"
	echo "Login to a Baseimage-based Docker container using nsenter." \
		"If COMMAND is not given, opens an interactive shell." \
		"Otherwise, runs COMMAND inside the container."
}

if test $# = 0; then
	usage
	exit
fi

# Check if the given container ID is valid and running
containerState=`docker inspect -f "{{ .State.Running }}" $1`;

if test containerState; then
	docker exec -t -i "$1" bash
else
	echo "ERROR: The provided container ID is either invalid or it's not running.";
fi